server:
  port: 8083

spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://config.platform:8888}"
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/eca_orders_db?connectTimeoutMS=2000&serverSelectionTimeoutMS=2000}
      auto-index-creation: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery.platform:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
